import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "@/components/navigation"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-gray-900 text-white flex flex-col">
          <Navigation />
          <main className="flex-grow">{children}</main>
          <footer className="bg-black py-6">
            <div className="container mx-auto px-4 text-center text-gray-400">
              <p>&copy; 2024 DegreeCompass. All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
